// <auto-generated />
namespace MvcLab.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class bckup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(bckup));
        
        string IMigrationMetadata.Id
        {
            get { return "201612021427072_bckup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
